# TicinpXP site, based on Evento Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: TicinoXP

#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Events

description: > # this means to ignore newlines until "baseurl:"
  Home page dello user group TicinoXP

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ticinoxp.github.io/"

author: Arialdo Martini
twitter_username: ticinoxp
github_username:  ticinoxp
company_name: 

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html

